Declare missing method for berkshelf
/home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/molinillo-0.2.3/lib/molinillo/resolution.rb:292:in `indicate_progress': undefined method `indicate_progress' for #<Solve::RubySolver:0x007f3d67eb08d8> (NoMethodError)
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/molinillo-0.2.3/lib/molinillo/resolution.rb:63:in `resolve'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/molinillo-0.2.3/lib/molinillo/resolver.rb:40:in `resolve'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/solve-2.0.1/lib/solve/ruby_solver.rb:177:in `resolve_with_error_wrapping'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/solve-2.0.1/lib/solve/ruby_solver.rb:72:in `resolve'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/solve-2.0.1/lib/solve.rb:64:in `it!'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/resolver.rb:76:in `resolve'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/installer.rb:175:in `install_from_universe'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/installer.rb:39:in `run'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/berksfile.rb:374:in `install'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/cli.rb:143:in `install'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/cli.rb:52:in `dispatch'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/lib/berkshelf/cli.rb:27:in `execute!'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bundler/gems/berkshelf-7a06112afd20/bin/berks:5:in `<top (required)>'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bin/berks:23:in `load'
        from /home/deploy/platform/infra/vendor/bundle/ruby/2.1.0/bin/berks:23:in `<main>'